-- 코드를 입력하세요
SELECT BOARD_ID
, WRITER_ID
, TITLE AS TITLE
, PRICE
, CASE 
    WHEN STATUS ='SALE' THEN '판매중'
    WHEN STATUS ='RESERVED' THEN '예약중'
    WHEN STATUS ='DONE' THEN '거래완료'
  END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = DATE_FORMAT('2022-10-5','%Y-%m-%d')
ORDER BY BOARD_ID DESC